# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rubikUI.ui'
#
# Created: Thu Jun 28 17:25:54 2018
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 530)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.q30 = QtGui.QGraphicsView(self.centralwidget)
        self.q30.setGeometry(QtCore.QRect(30, 175, 40, 40))
        self.q30.setObjectName("q30")
        self.q31 = QtGui.QGraphicsView(self.centralwidget)
        self.q31.setGeometry(QtCore.QRect(80, 175, 40, 40))
        self.q31.setObjectName("q31")
        self.q52 = QtGui.QGraphicsView(self.centralwidget)
        self.q52.setGeometry(QtCore.QRect(130, 275, 40, 40))
        self.q52.setObjectName("q52")
        self.q32 = QtGui.QGraphicsView(self.centralwidget)
        self.q32.setGeometry(QtCore.QRect(130, 175, 40, 40))
        self.q32.setObjectName("q32")
        self.q40 = QtGui.QGraphicsView(self.centralwidget)
        self.q40.setGeometry(QtCore.QRect(30, 225, 40, 40))
        self.q40.setObjectName("q40")
        self.q41 = QtGui.QGraphicsView(self.centralwidget)
        self.q41.setGeometry(QtCore.QRect(80, 225, 40, 40))
        self.q41.setObjectName("q41")
        self.q42 = QtGui.QGraphicsView(self.centralwidget)
        self.q42.setGeometry(QtCore.QRect(130, 225, 40, 40))
        self.q42.setObjectName("q42")
        self.q50 = QtGui.QGraphicsView(self.centralwidget)
        self.q50.setGeometry(QtCore.QRect(30, 275, 40, 40))
        self.q50.setObjectName("q50")
        self.q51 = QtGui.QGraphicsView(self.centralwidget)
        self.q51.setGeometry(QtCore.QRect(80, 275, 40, 40))
        self.q51.setObjectName("q51")
        self.q23 = QtGui.QGraphicsView(self.centralwidget)
        self.q23.setGeometry(QtCore.QRect(180, 125, 40, 40))
        self.q23.setObjectName("q23")
        self.q03 = QtGui.QGraphicsView(self.centralwidget)
        self.q03.setGeometry(QtCore.QRect(180, 25, 40, 40))
        self.q03.setObjectName("q03")
        self.q14 = QtGui.QGraphicsView(self.centralwidget)
        self.q14.setGeometry(QtCore.QRect(230, 75, 40, 40))
        self.q14.setObjectName("q14")
        self.q24 = QtGui.QGraphicsView(self.centralwidget)
        self.q24.setGeometry(QtCore.QRect(230, 125, 40, 40))
        self.q24.setObjectName("q24")
        self.q25 = QtGui.QGraphicsView(self.centralwidget)
        self.q25.setGeometry(QtCore.QRect(280, 125, 40, 40))
        self.q25.setObjectName("q25")
        self.q05 = QtGui.QGraphicsView(self.centralwidget)
        self.q05.setGeometry(QtCore.QRect(280, 25, 40, 40))
        self.q05.setObjectName("q05")
        self.q15 = QtGui.QGraphicsView(self.centralwidget)
        self.q15.setGeometry(QtCore.QRect(280, 75, 40, 40))
        self.q15.setObjectName("q15")
        self.q04 = QtGui.QGraphicsView(self.centralwidget)
        self.q04.setGeometry(QtCore.QRect(230, 25, 40, 40))
        self.q04.setObjectName("q04")
        self.q13 = QtGui.QGraphicsView(self.centralwidget)
        self.q13.setGeometry(QtCore.QRect(180, 75, 40, 40))
        self.q13.setObjectName("q13")
        self.q44 = QtGui.QGraphicsView(self.centralwidget)
        self.q44.setGeometry(QtCore.QRect(230, 225, 40, 40))
        self.q44.setObjectName("q44")
        self.q34 = QtGui.QGraphicsView(self.centralwidget)
        self.q34.setGeometry(QtCore.QRect(230, 175, 40, 40))
        self.q34.setObjectName("q34")
        self.q35 = QtGui.QGraphicsView(self.centralwidget)
        self.q35.setGeometry(QtCore.QRect(280, 175, 40, 40))
        self.q35.setObjectName("q35")
        self.q33 = QtGui.QGraphicsView(self.centralwidget)
        self.q33.setGeometry(QtCore.QRect(180, 175, 40, 40))
        self.q33.setObjectName("q33")
        self.q55 = QtGui.QGraphicsView(self.centralwidget)
        self.q55.setGeometry(QtCore.QRect(280, 275, 40, 40))
        self.q55.setObjectName("q55")
        self.q45 = QtGui.QGraphicsView(self.centralwidget)
        self.q45.setGeometry(QtCore.QRect(280, 225, 40, 40))
        self.q45.setObjectName("q45")
        self.q54 = QtGui.QGraphicsView(self.centralwidget)
        self.q54.setGeometry(QtCore.QRect(230, 275, 40, 40))
        self.q54.setObjectName("q54")
        self.q53 = QtGui.QGraphicsView(self.centralwidget)
        self.q53.setGeometry(QtCore.QRect(180, 275, 40, 40))
        self.q53.setObjectName("q53")
        self.q43 = QtGui.QGraphicsView(self.centralwidget)
        self.q43.setGeometry(QtCore.QRect(180, 225, 40, 40))
        self.q43.setObjectName("q43")
        self.q47 = QtGui.QGraphicsView(self.centralwidget)
        self.q47.setGeometry(QtCore.QRect(380, 225, 40, 40))
        self.q47.setObjectName("q47")
        self.q37 = QtGui.QGraphicsView(self.centralwidget)
        self.q37.setGeometry(QtCore.QRect(380, 175, 40, 40))
        self.q37.setObjectName("q37")
        self.q38 = QtGui.QGraphicsView(self.centralwidget)
        self.q38.setGeometry(QtCore.QRect(430, 175, 40, 40))
        self.q38.setObjectName("q38")
        self.q36 = QtGui.QGraphicsView(self.centralwidget)
        self.q36.setGeometry(QtCore.QRect(330, 175, 40, 40))
        self.q36.setObjectName("q36")
        self.q58 = QtGui.QGraphicsView(self.centralwidget)
        self.q58.setGeometry(QtCore.QRect(430, 275, 40, 40))
        self.q58.setObjectName("q58")
        self.q48 = QtGui.QGraphicsView(self.centralwidget)
        self.q48.setGeometry(QtCore.QRect(430, 225, 40, 40))
        self.q48.setObjectName("q48")
        self.q57 = QtGui.QGraphicsView(self.centralwidget)
        self.q57.setGeometry(QtCore.QRect(380, 275, 40, 40))
        self.q57.setObjectName("q57")
        self.q56 = QtGui.QGraphicsView(self.centralwidget)
        self.q56.setGeometry(QtCore.QRect(330, 275, 40, 40))
        self.q56.setObjectName("q56")
        self.q46 = QtGui.QGraphicsView(self.centralwidget)
        self.q46.setGeometry(QtCore.QRect(330, 225, 40, 40))
        self.q46.setObjectName("q46")
        self.q410 = QtGui.QGraphicsView(self.centralwidget)
        self.q410.setGeometry(QtCore.QRect(530, 225, 40, 40))
        self.q410.setObjectName("q410")
        self.q310 = QtGui.QGraphicsView(self.centralwidget)
        self.q310.setGeometry(QtCore.QRect(530, 175, 40, 40))
        self.q310.setObjectName("q310")
        self.q311 = QtGui.QGraphicsView(self.centralwidget)
        self.q311.setGeometry(QtCore.QRect(580, 175, 40, 40))
        self.q311.setObjectName("q311")
        self.q39 = QtGui.QGraphicsView(self.centralwidget)
        self.q39.setGeometry(QtCore.QRect(480, 175, 40, 40))
        self.q39.setObjectName("q39")
        self.q511 = QtGui.QGraphicsView(self.centralwidget)
        self.q511.setGeometry(QtCore.QRect(580, 275, 40, 40))
        self.q511.setObjectName("q511")
        self.q411 = QtGui.QGraphicsView(self.centralwidget)
        self.q411.setGeometry(QtCore.QRect(580, 225, 40, 40))
        self.q411.setObjectName("q411")
        self.q510 = QtGui.QGraphicsView(self.centralwidget)
        self.q510.setGeometry(QtCore.QRect(530, 275, 40, 40))
        self.q510.setObjectName("q510")
        self.q59 = QtGui.QGraphicsView(self.centralwidget)
        self.q59.setGeometry(QtCore.QRect(480, 275, 40, 40))
        self.q59.setObjectName("q59")
        self.q49 = QtGui.QGraphicsView(self.centralwidget)
        self.q49.setGeometry(QtCore.QRect(480, 225, 40, 40))
        self.q49.setObjectName("q49")
        self.q74 = QtGui.QGraphicsView(self.centralwidget)
        self.q74.setGeometry(QtCore.QRect(230, 375, 40, 40))
        self.q74.setObjectName("q74")
        self.q64 = QtGui.QGraphicsView(self.centralwidget)
        self.q64.setGeometry(QtCore.QRect(230, 325, 40, 40))
        self.q64.setObjectName("q64")
        self.q65 = QtGui.QGraphicsView(self.centralwidget)
        self.q65.setGeometry(QtCore.QRect(280, 325, 40, 40))
        self.q65.setObjectName("q65")
        self.q63 = QtGui.QGraphicsView(self.centralwidget)
        self.q63.setGeometry(QtCore.QRect(180, 325, 40, 40))
        self.q63.setObjectName("q63")
        self.q85 = QtGui.QGraphicsView(self.centralwidget)
        self.q85.setGeometry(QtCore.QRect(280, 425, 40, 40))
        self.q85.setObjectName("q85")
        self.q75 = QtGui.QGraphicsView(self.centralwidget)
        self.q75.setGeometry(QtCore.QRect(280, 375, 40, 40))
        self.q75.setObjectName("q75")
        self.q84 = QtGui.QGraphicsView(self.centralwidget)
        self.q84.setGeometry(QtCore.QRect(230, 425, 40, 40))
        self.q84.setObjectName("q84")
        self.q83 = QtGui.QGraphicsView(self.centralwidget)
        self.q83.setGeometry(QtCore.QRect(180, 425, 40, 40))
        self.q83.setObjectName("q83")
        self.q73 = QtGui.QGraphicsView(self.centralwidget)
        self.q73.setGeometry(QtCore.QRect(180, 375, 40, 40))
        self.q73.setObjectName("q73")
        self.btnScramble = QtGui.QPushButton(self.centralwidget)
        self.btnScramble.setGeometry(QtCore.QRect(835, 105, 80, 80))
        self.btnScramble.setObjectName("btnScramble")
        self.btnSolve = QtGui.QPushButton(self.centralwidget)
        self.btnSolve.setGeometry(QtCore.QRect(835, 275, 80, 80))
        self.btnSolve.setObjectName("btnSolve")
        self.sliSpeed = QtGui.QSlider(self.centralwidget)
        self.sliSpeed.setGeometry(QtCore.QRect(670, 405, 241, 20))
        self.sliSpeed.setSliderPosition(80)
        self.sliSpeed.setOrientation(QtCore.Qt.Horizontal)
        self.sliSpeed.setTickPosition(QtGui.QSlider.NoTicks)
        self.sliSpeed.setObjectName("sliSpeed")
        self.proDone = QtGui.QProgressBar(self.centralwidget)
        self.proDone.setEnabled(True)
        self.proDone.setGeometry(QtCore.QRect(30, 485, 591, 23))
        self.proDone.setProperty("value", 100)
        self.proDone.setOrientation(QtCore.Qt.Horizontal)
        self.proDone.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.proDone.setObjectName("proDone")
        self.btnU = QtGui.QPushButton(self.centralwidget)
        self.btnU.setGeometry(QtCore.QRect(665, 70, 50, 50))
        self.btnU.setObjectName("btnU")
        self.btnU2 = QtGui.QPushButton(self.centralwidget)
        self.btnU2.setGeometry(QtCore.QRect(775, 70, 50, 50))
        self.btnU2.setObjectName("btnU2")
        self.btnUp = QtGui.QPushButton(self.centralwidget)
        self.btnUp.setGeometry(QtCore.QRect(720, 70, 50, 50))
        self.btnUp.setObjectName("btnUp")
        self.btnD = QtGui.QPushButton(self.centralwidget)
        self.btnD.setGeometry(QtCore.QRect(665, 125, 50, 50))
        self.btnD.setObjectName("btnD")
        self.btnDp = QtGui.QPushButton(self.centralwidget)
        self.btnDp.setGeometry(QtCore.QRect(720, 125, 50, 50))
        self.btnDp.setObjectName("btnDp")
        self.btnD2 = QtGui.QPushButton(self.centralwidget)
        self.btnD2.setGeometry(QtCore.QRect(775, 125, 50, 50))
        self.btnD2.setObjectName("btnD2")
        self.btnL = QtGui.QPushButton(self.centralwidget)
        self.btnL.setGeometry(QtCore.QRect(665, 180, 50, 50))
        self.btnL.setObjectName("btnL")
        self.btnLp = QtGui.QPushButton(self.centralwidget)
        self.btnLp.setGeometry(QtCore.QRect(720, 180, 50, 50))
        self.btnLp.setObjectName("btnLp")
        self.btnL2 = QtGui.QPushButton(self.centralwidget)
        self.btnL2.setGeometry(QtCore.QRect(775, 180, 50, 50))
        self.btnL2.setObjectName("btnL2")
        self.btnR = QtGui.QPushButton(self.centralwidget)
        self.btnR.setGeometry(QtCore.QRect(665, 235, 50, 50))
        self.btnR.setObjectName("btnR")
        self.btnRp = QtGui.QPushButton(self.centralwidget)
        self.btnRp.setGeometry(QtCore.QRect(720, 235, 50, 50))
        self.btnRp.setObjectName("btnRp")
        self.btnR2 = QtGui.QPushButton(self.centralwidget)
        self.btnR2.setGeometry(QtCore.QRect(775, 235, 50, 50))
        self.btnR2.setObjectName("btnR2")
        self.btnF = QtGui.QPushButton(self.centralwidget)
        self.btnF.setGeometry(QtCore.QRect(665, 290, 50, 50))
        self.btnF.setObjectName("btnF")
        self.btnFp = QtGui.QPushButton(self.centralwidget)
        self.btnFp.setGeometry(QtCore.QRect(720, 290, 50, 50))
        self.btnFp.setObjectName("btnFp")
        self.btnF2 = QtGui.QPushButton(self.centralwidget)
        self.btnF2.setGeometry(QtCore.QRect(775, 290, 50, 50))
        self.btnF2.setObjectName("btnF2")
        self.btnB = QtGui.QPushButton(self.centralwidget)
        self.btnB.setGeometry(QtCore.QRect(665, 345, 50, 50))
        self.btnB.setObjectName("btnB")
        self.btnBp = QtGui.QPushButton(self.centralwidget)
        self.btnBp.setGeometry(QtCore.QRect(720, 345, 50, 50))
        self.btnBp.setObjectName("btnBp")
        self.btnB2 = QtGui.QPushButton(self.centralwidget)
        self.btnB2.setGeometry(QtCore.QRect(775, 345, 50, 50))
        self.btnB2.setObjectName("btnB2")
        self.qB1 = QtGui.QGraphicsView(self.centralwidget)
        self.qB1.setGeometry(QtCore.QRect(25, 170, 600, 151))
        self.qB1.setObjectName("qB1")
        self.qB2 = QtGui.QGraphicsView(self.centralwidget)
        self.qB2.setGeometry(QtCore.QRect(175, 20, 151, 450))
        self.qB2.setObjectName("qB2")
        self.qB3 = QtGui.QGraphicsView(self.centralwidget)
        self.qB3.setGeometry(QtCore.QRect(655, 60, 270, 375))
        self.qB3.setObjectName("qB3")
        self.l4 = QtGui.QFrame(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(175, 465, 150, 10))
        self.l4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l4.setFrameShadow(QtGui.QFrame.Plain)
        self.l4.setFrameShape(QtGui.QFrame.HLine)
        self.l4.setFrameShadow(QtGui.QFrame.Sunken)
        self.l4.setObjectName("l4")
        self.l10 = QtGui.QFrame(self.centralwidget)
        self.l10.setGeometry(QtCore.QRect(655, 55, 270, 10))
        self.l10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l10.setFrameShadow(QtGui.QFrame.Plain)
        self.l10.setFrameShape(QtGui.QFrame.HLine)
        self.l10.setFrameShadow(QtGui.QFrame.Sunken)
        self.l10.setObjectName("l10")
        self.l1 = QtGui.QFrame(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(25, 165, 600, 10))
        self.l1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l1.setFrameShadow(QtGui.QFrame.Plain)
        self.l1.setFrameShape(QtGui.QFrame.HLine)
        self.l1.setFrameShadow(QtGui.QFrame.Sunken)
        self.l1.setObjectName("l1")
        self.l3 = QtGui.QFrame(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(175, 15, 150, 10))
        self.l3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l3.setFrameShadow(QtGui.QFrame.Plain)
        self.l3.setFrameShape(QtGui.QFrame.HLine)
        self.l3.setFrameShadow(QtGui.QFrame.Sunken)
        self.l3.setObjectName("l3")
        self.l7 = QtGui.QFrame(self.centralwidget)
        self.l7.setGeometry(QtCore.QRect(20, 170, 10, 150))
        self.l7.setFrameShadow(QtGui.QFrame.Plain)
        self.l7.setFrameShape(QtGui.QFrame.VLine)
        self.l7.setFrameShadow(QtGui.QFrame.Sunken)
        self.l7.setObjectName("l7")
        self.l9 = QtGui.QFrame(self.centralwidget)
        self.l9.setGeometry(QtCore.QRect(620, 170, 10, 150))
        self.l9.setFrameShadow(QtGui.QFrame.Plain)
        self.l9.setFrameShape(QtGui.QFrame.VLine)
        self.l9.setFrameShadow(QtGui.QFrame.Sunken)
        self.l9.setObjectName("l9")
        self.l8 = QtGui.QFrame(self.centralwidget)
        self.l8.setGeometry(QtCore.QRect(470, 170, 10, 150))
        self.l8.setFrameShadow(QtGui.QFrame.Plain)
        self.l8.setFrameShape(QtGui.QFrame.VLine)
        self.l8.setFrameShadow(QtGui.QFrame.Sunken)
        self.l8.setObjectName("l8")
        self.l6 = QtGui.QFrame(self.centralwidget)
        self.l6.setGeometry(QtCore.QRect(320, 20, 10, 450))
        self.l6.setFrameShadow(QtGui.QFrame.Plain)
        self.l6.setFrameShape(QtGui.QFrame.VLine)
        self.l6.setFrameShadow(QtGui.QFrame.Sunken)
        self.l6.setObjectName("l6")
        self.l5 = QtGui.QFrame(self.centralwidget)
        self.l5.setGeometry(QtCore.QRect(170, 20, 10, 450))
        self.l5.setFrameShadow(QtGui.QFrame.Plain)
        self.l5.setFrameShape(QtGui.QFrame.VLine)
        self.l5.setFrameShadow(QtGui.QFrame.Sunken)
        self.l5.setObjectName("l5")
        self.l13 = QtGui.QFrame(self.centralwidget)
        self.l13.setGeometry(QtCore.QRect(920, 60, 10, 375))
        self.l13.setFrameShadow(QtGui.QFrame.Plain)
        self.l13.setFrameShape(QtGui.QFrame.VLine)
        self.l13.setFrameShadow(QtGui.QFrame.Sunken)
        self.l13.setObjectName("l13")
        self.l11 = QtGui.QFrame(self.centralwidget)
        self.l11.setGeometry(QtCore.QRect(655, 430, 270, 10))
        self.l11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l11.setFrameShadow(QtGui.QFrame.Plain)
        self.l11.setFrameShape(QtGui.QFrame.HLine)
        self.l11.setFrameShadow(QtGui.QFrame.Sunken)
        self.l11.setObjectName("l11")
        self.l2 = QtGui.QFrame(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(25, 315, 600, 10))
        self.l2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l2.setFrameShadow(QtGui.QFrame.Plain)
        self.l2.setFrameShape(QtGui.QFrame.HLine)
        self.l2.setFrameShadow(QtGui.QFrame.Sunken)
        self.l2.setObjectName("l2")
        self.l12 = QtGui.QFrame(self.centralwidget)
        self.l12.setGeometry(QtCore.QRect(650, 60, 10, 375))
        self.l12.setFrameShadow(QtGui.QFrame.Plain)
        self.l12.setFrameShape(QtGui.QFrame.VLine)
        self.l12.setFrameShadow(QtGui.QFrame.Sunken)
        self.l12.setObjectName("l12")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.btnScramble.setText(QtGui.QApplication.translate("MainWindow", "Scramble", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSolve.setText(QtGui.QApplication.translate("MainWindow", "Solve", None, QtGui.QApplication.UnicodeUTF8))
        self.btnU.setText(QtGui.QApplication.translate("MainWindow", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.btnU2.setText(QtGui.QApplication.translate("MainWindow", "U2", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUp.setText(QtGui.QApplication.translate("MainWindow", "U\'", None, QtGui.QApplication.UnicodeUTF8))
        self.btnD.setText(QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDp.setText(QtGui.QApplication.translate("MainWindow", "D\'", None, QtGui.QApplication.UnicodeUTF8))
        self.btnD2.setText(QtGui.QApplication.translate("MainWindow", "D2", None, QtGui.QApplication.UnicodeUTF8))
        self.btnL.setText(QtGui.QApplication.translate("MainWindow", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLp.setText(QtGui.QApplication.translate("MainWindow", "L\'", None, QtGui.QApplication.UnicodeUTF8))
        self.btnL2.setText(QtGui.QApplication.translate("MainWindow", "L2", None, QtGui.QApplication.UnicodeUTF8))
        self.btnR.setText(QtGui.QApplication.translate("MainWindow", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRp.setText(QtGui.QApplication.translate("MainWindow", "R\'", None, QtGui.QApplication.UnicodeUTF8))
        self.btnR2.setText(QtGui.QApplication.translate("MainWindow", "R2", None, QtGui.QApplication.UnicodeUTF8))
        self.btnF.setText(QtGui.QApplication.translate("MainWindow", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFp.setText(QtGui.QApplication.translate("MainWindow", "F\'", None, QtGui.QApplication.UnicodeUTF8))
        self.btnF2.setText(QtGui.QApplication.translate("MainWindow", "F2", None, QtGui.QApplication.UnicodeUTF8))
        self.btnB.setText(QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBp.setText(QtGui.QApplication.translate("MainWindow", "B\'", None, QtGui.QApplication.UnicodeUTF8))
        self.btnB2.setText(QtGui.QApplication.translate("MainWindow", "B2", None, QtGui.QApplication.UnicodeUTF8))

