# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rubikUI.ui'
#
# Created: Thu Jun 28 14:06:41 2018
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.q30 = QtGui.QGraphicsView(self.centralwidget)
        self.q30.setGeometry(QtCore.QRect(10, 160, 40, 40))
        self.q30.setObjectName("q30")
        self.q31 = QtGui.QGraphicsView(self.centralwidget)
        self.q31.setGeometry(QtCore.QRect(60, 160, 40, 40))
        self.q31.setObjectName("q31")
        self.q52 = QtGui.QGraphicsView(self.centralwidget)
        self.q52.setGeometry(QtCore.QRect(110, 260, 40, 40))
        self.q52.setObjectName("q52")
        self.q32 = QtGui.QGraphicsView(self.centralwidget)
        self.q32.setGeometry(QtCore.QRect(110, 160, 40, 40))
        self.q32.setObjectName("q32")
        self.q40 = QtGui.QGraphicsView(self.centralwidget)
        self.q40.setGeometry(QtCore.QRect(10, 210, 40, 40))
        self.q40.setObjectName("q40")
        self.q41 = QtGui.QGraphicsView(self.centralwidget)
        self.q41.setGeometry(QtCore.QRect(60, 210, 40, 40))
        self.q41.setObjectName("q41")
        self.q42 = QtGui.QGraphicsView(self.centralwidget)
        self.q42.setGeometry(QtCore.QRect(110, 210, 40, 40))
        self.q42.setObjectName("q42")
        self.q50 = QtGui.QGraphicsView(self.centralwidget)
        self.q50.setGeometry(QtCore.QRect(10, 260, 40, 40))
        self.q50.setObjectName("q50")
        self.q51 = QtGui.QGraphicsView(self.centralwidget)
        self.q51.setGeometry(QtCore.QRect(60, 260, 40, 40))
        self.q51.setObjectName("q51")
        self.q23 = QtGui.QGraphicsView(self.centralwidget)
        self.q23.setGeometry(QtCore.QRect(160, 110, 40, 40))
        self.q23.setObjectName("q23")
        self.q03 = QtGui.QGraphicsView(self.centralwidget)
        self.q03.setGeometry(QtCore.QRect(160, 10, 40, 40))
        self.q03.setObjectName("q03")
        self.q14 = QtGui.QGraphicsView(self.centralwidget)
        self.q14.setGeometry(QtCore.QRect(210, 60, 40, 40))
        self.q14.setObjectName("q14")
        self.q24 = QtGui.QGraphicsView(self.centralwidget)
        self.q24.setGeometry(QtCore.QRect(210, 110, 40, 40))
        self.q24.setObjectName("q24")
        self.q25 = QtGui.QGraphicsView(self.centralwidget)
        self.q25.setGeometry(QtCore.QRect(260, 110, 40, 40))
        self.q25.setObjectName("q25")
        self.q05 = QtGui.QGraphicsView(self.centralwidget)
        self.q05.setGeometry(QtCore.QRect(260, 10, 40, 40))
        self.q05.setObjectName("q05")
        self.q15 = QtGui.QGraphicsView(self.centralwidget)
        self.q15.setGeometry(QtCore.QRect(260, 60, 40, 40))
        self.q15.setObjectName("q15")
        self.q04 = QtGui.QGraphicsView(self.centralwidget)
        self.q04.setGeometry(QtCore.QRect(210, 10, 40, 40))
        self.q04.setObjectName("q04")
        self.q13 = QtGui.QGraphicsView(self.centralwidget)
        self.q13.setGeometry(QtCore.QRect(160, 60, 40, 40))
        self.q13.setObjectName("q13")
        self.q44 = QtGui.QGraphicsView(self.centralwidget)
        self.q44.setGeometry(QtCore.QRect(210, 210, 40, 40))
        self.q44.setObjectName("q44")
        self.q34 = QtGui.QGraphicsView(self.centralwidget)
        self.q34.setGeometry(QtCore.QRect(210, 160, 40, 40))
        self.q34.setObjectName("q34")
        self.q35 = QtGui.QGraphicsView(self.centralwidget)
        self.q35.setGeometry(QtCore.QRect(260, 160, 40, 40))
        self.q35.setObjectName("q35")
        self.q33 = QtGui.QGraphicsView(self.centralwidget)
        self.q33.setGeometry(QtCore.QRect(160, 160, 40, 40))
        self.q33.setObjectName("q33")
        self.q55 = QtGui.QGraphicsView(self.centralwidget)
        self.q55.setGeometry(QtCore.QRect(260, 260, 40, 40))
        self.q55.setObjectName("q55")
        self.q45 = QtGui.QGraphicsView(self.centralwidget)
        self.q45.setGeometry(QtCore.QRect(260, 210, 40, 40))
        self.q45.setObjectName("q45")
        self.q54 = QtGui.QGraphicsView(self.centralwidget)
        self.q54.setGeometry(QtCore.QRect(210, 260, 40, 40))
        self.q54.setObjectName("q54")
        self.q53 = QtGui.QGraphicsView(self.centralwidget)
        self.q53.setGeometry(QtCore.QRect(160, 260, 40, 40))
        self.q53.setObjectName("q53")
        self.q43 = QtGui.QGraphicsView(self.centralwidget)
        self.q43.setGeometry(QtCore.QRect(160, 210, 40, 40))
        self.q43.setObjectName("q43")
        self.q47 = QtGui.QGraphicsView(self.centralwidget)
        self.q47.setGeometry(QtCore.QRect(360, 210, 40, 40))
        self.q47.setObjectName("q47")
        self.q37 = QtGui.QGraphicsView(self.centralwidget)
        self.q37.setGeometry(QtCore.QRect(360, 160, 40, 40))
        self.q37.setObjectName("q37")
        self.q38 = QtGui.QGraphicsView(self.centralwidget)
        self.q38.setGeometry(QtCore.QRect(410, 160, 40, 40))
        self.q38.setObjectName("q38")
        self.q36 = QtGui.QGraphicsView(self.centralwidget)
        self.q36.setGeometry(QtCore.QRect(310, 160, 40, 40))
        self.q36.setObjectName("q36")
        self.q58 = QtGui.QGraphicsView(self.centralwidget)
        self.q58.setGeometry(QtCore.QRect(410, 260, 40, 40))
        self.q58.setObjectName("q58")
        self.q48 = QtGui.QGraphicsView(self.centralwidget)
        self.q48.setGeometry(QtCore.QRect(410, 210, 40, 40))
        self.q48.setObjectName("q48")
        self.q57 = QtGui.QGraphicsView(self.centralwidget)
        self.q57.setGeometry(QtCore.QRect(360, 260, 40, 40))
        self.q57.setObjectName("q57")
        self.q56 = QtGui.QGraphicsView(self.centralwidget)
        self.q56.setGeometry(QtCore.QRect(310, 260, 40, 40))
        self.q56.setObjectName("q56")
        self.q46 = QtGui.QGraphicsView(self.centralwidget)
        self.q46.setGeometry(QtCore.QRect(310, 210, 40, 40))
        self.q46.setObjectName("q46")
        self.q410 = QtGui.QGraphicsView(self.centralwidget)
        self.q410.setGeometry(QtCore.QRect(510, 210, 40, 40))
        self.q410.setObjectName("q410")
        self.q310 = QtGui.QGraphicsView(self.centralwidget)
        self.q310.setGeometry(QtCore.QRect(510, 160, 40, 40))
        self.q310.setObjectName("q310")
        self.q311 = QtGui.QGraphicsView(self.centralwidget)
        self.q311.setGeometry(QtCore.QRect(560, 160, 40, 40))
        self.q311.setObjectName("q311")
        self.q39 = QtGui.QGraphicsView(self.centralwidget)
        self.q39.setGeometry(QtCore.QRect(460, 160, 40, 40))
        self.q39.setObjectName("q39")
        self.q511 = QtGui.QGraphicsView(self.centralwidget)
        self.q511.setGeometry(QtCore.QRect(560, 260, 40, 40))
        self.q511.setObjectName("q511")
        self.q411 = QtGui.QGraphicsView(self.centralwidget)
        self.q411.setGeometry(QtCore.QRect(560, 210, 40, 40))
        self.q411.setObjectName("q411")
        self.q510 = QtGui.QGraphicsView(self.centralwidget)
        self.q510.setGeometry(QtCore.QRect(510, 260, 40, 40))
        self.q510.setObjectName("q510")
        self.q59 = QtGui.QGraphicsView(self.centralwidget)
        self.q59.setGeometry(QtCore.QRect(460, 260, 40, 40))
        self.q59.setObjectName("q59")
        self.q49 = QtGui.QGraphicsView(self.centralwidget)
        self.q49.setGeometry(QtCore.QRect(460, 210, 40, 40))
        self.q49.setObjectName("q49")
        self.q74 = QtGui.QGraphicsView(self.centralwidget)
        self.q74.setGeometry(QtCore.QRect(210, 360, 40, 40))
        self.q74.setObjectName("q74")
        self.q64 = QtGui.QGraphicsView(self.centralwidget)
        self.q64.setGeometry(QtCore.QRect(210, 310, 40, 40))
        self.q64.setObjectName("q64")
        self.q65 = QtGui.QGraphicsView(self.centralwidget)
        self.q65.setGeometry(QtCore.QRect(260, 310, 40, 40))
        self.q65.setObjectName("q65")
        self.q63 = QtGui.QGraphicsView(self.centralwidget)
        self.q63.setGeometry(QtCore.QRect(160, 310, 40, 40))
        self.q63.setObjectName("q63")
        self.q85 = QtGui.QGraphicsView(self.centralwidget)
        self.q85.setGeometry(QtCore.QRect(260, 410, 40, 40))
        self.q85.setObjectName("q85")
        self.q75 = QtGui.QGraphicsView(self.centralwidget)
        self.q75.setGeometry(QtCore.QRect(260, 360, 40, 40))
        self.q75.setObjectName("q75")
        self.q84 = QtGui.QGraphicsView(self.centralwidget)
        self.q84.setGeometry(QtCore.QRect(210, 410, 40, 40))
        self.q84.setObjectName("q84")
        self.q83 = QtGui.QGraphicsView(self.centralwidget)
        self.q83.setGeometry(QtCore.QRect(160, 410, 40, 40))
        self.q83.setObjectName("q83")
        self.q73 = QtGui.QGraphicsView(self.centralwidget)
        self.q73.setGeometry(QtCore.QRect(160, 360, 40, 40))
        self.q73.setObjectName("q73")
        self.btnScramble = QtGui.QPushButton(self.centralwidget)
        self.btnScramble.setGeometry(QtCore.QRect(340, 320, 80, 80))
        self.btnScramble.setObjectName("btnScramble")
        self.btnSolve = QtGui.QPushButton(self.centralwidget)
        self.btnSolve.setGeometry(QtCore.QRect(490, 320, 80, 80))
        self.btnSolve.setObjectName("btnSolve")
        self.sliSpeed = QtGui.QSlider(self.centralwidget)
        self.sliSpeed.setGeometry(QtCore.QRect(340, 420, 231, 20))
        self.sliSpeed.setSliderPosition(75)
        self.sliSpeed.setOrientation(QtCore.Qt.Horizontal)
        self.sliSpeed.setTickPosition(QtGui.QSlider.NoTicks)
        self.sliSpeed.setObjectName("sliSpeed")
        self.proDone = QtGui.QProgressBar(self.centralwidget)
        self.proDone.setEnabled(True)
        self.proDone.setGeometry(QtCore.QRect(10, 470, 591, 23))
        self.proDone.setProperty("value", 100)
        self.proDone.setOrientation(QtCore.Qt.Horizontal)
        self.proDone.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.proDone.setObjectName("proDone")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.btnScramble.setText(QtGui.QApplication.translate("MainWindow", "Scramble", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSolve.setText(QtGui.QApplication.translate("MainWindow", "Solve", None, QtGui.QApplication.UnicodeUTF8))

